site_name: wavi-web

repo_url: https://github.com/thozwa/wavi-web
repo_name: wavi-web
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Get Started: get_started.md
  - Blog:
    - blog/index.md
  - Community:
    - community.md

theme:
  name: material
  custom_dir: docs/assets
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: https://raw.githubusercontent.com/RJArthern/WAVI.jl/build-docs/docs/src/assets/logo.png
  favicon: images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    # Enables copying of code blocks
    - content.code.copy
    # Enables "edit this page" to contribute to docs
    - content.action.edit
    - navigation.indexes
    - navigation.tabs
plugins:
  - blog
  - search
  # Enables automatically generating authors from git repo, see acknowledgements.md
markdown_extensions:
  - admonition
  # Enables code block highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
copyright: Copyright &copy; 2025 British Antarctic Survey

# Custom Homepage Elements
home_cover_image: https://raw.githubusercontent.com/RJArthern/WAVI.jl/build-docs/docs/src/assets/logo.png
home_tagline: WAVI
home_description: |
  WAVI (Wavelet-based Adaptive-grid Vertically-integrated Ice-model) is a fast and friendly ice sheet model, written in Julia.

# Gradient Color
home_gradient_hsla: hsla(0deg,47%,55%,1) # Default Green: hsla(160deg,47%,55%,1)

# Custom Homepage Button(s)
home_button1_name: Get Started                  
home_button1_url: getting_started/
home_button1_theme: md-button md-button--primary 

home_button2_name: Blog  
home_button2_url: blog/
home_button2_theme: md-button

home_button3_name: Community
home_button3_url: Folder3/
home_button3_theme: md-button

